from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train/test Birkin-vs-not-Birkin KNN classifier on mixed dataset using EigenBags."
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=Path("outputs/mixed_dataset.npz"),
        help="Path to NPZ file generated by data_mixer.py",
    )
    parser.add_argument("--components", type=int, default=48, help="Number of PCA components.")
    parser.add_argument("--k", type=int, default=5, help="Number of KNN neighbors.")
    parser.add_argument("--test-size", type=float, default=0.2, help="Evaluation split size.")
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    parser.add_argument(
        "--report-path",
        type=Path,
        default=Path("outputs/classification_report.txt"),
        help="Where to save text report.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.dataset.exists():
        raise FileNotFoundError(f"Dataset not found: {args.dataset}. Run data_mixer.py first.")

    data = np.load(args.dataset, allow_pickle=True)
    x = data["X"]
    y = data["y"]

    x_train, x_test, y_train, y_test = train_test_split(
        x,
        y,
        test_size=args.test_size,
        random_state=args.seed,
        stratify=y,
    )

    n_components = min(args.components, x_train.shape[0], x_train.shape[1])
    if n_components < 1:
        raise ValueError("n_components must be >= 1")

    pca = PCA(n_components=n_components, svd_solver="randomized", whiten=True, random_state=args.seed)
    x_train_pca = pca.fit_transform(x_train)
    x_test_pca = pca.transform(x_test)

    model = KNeighborsClassifier(n_neighbors=args.k, weights="distance")
    model.fit(x_train_pca, y_train)
    predictions = model.predict(x_test_pca)

    accuracy = float((predictions == y_test).mean())
    cm = confusion_matrix(y_test, predictions)
    report = classification_report(y_test, predictions, target_names=["not_birkin", "birkin"], digits=4)

    args.report_path.parent.mkdir(parents=True, exist_ok=True)
    with args.report_path.open("w", encoding="utf-8") as file:
        file.write("EigenBags + KNN classification\n")
        file.write(f"dataset={args.dataset}\n")
        file.write(f"total_samples={len(x)}\n")
        file.write(f"birkin_samples={int(y.sum())}\n")
        file.write(f"not_birkin_samples={len(y) - int(y.sum())}\n")
        file.write(f"train_samples={len(x_train)}\n")
        file.write(f"test_samples={len(x_test)}\n")
        file.write(f"n_components={n_components}\n")
        file.write(f"k={args.k}\n")
        file.write(f"accuracy={accuracy:.4f}\n\n")
        file.write("Confusion matrix [[TN, FP], [FN, TP]]:\n")
        file.write(f"{cm}\n\n")
        file.write(report)

    print(f"Accuracy: {accuracy:.4f}")
    print(cm)
    print(report)
    print(f"Saved report: {args.report_path}")


if __name__ == "__main__":
    main()
